version: '3'
services:
  nginx:
    image: nginx
    ports:
      - 2333:2333
    links:
      - fpm
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nextcloud:/var/www/html
    restart: always
    depends_on:
      - fpm

  mariadb:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=kuaizi
      - MYSQL_PASSWORD=kuaizi
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    restart: always

  fpm:
    image: nextcloud:fpm
    links:
      - mariadb
    volumes:
      - ./nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=kuaizi
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=mariadb
    restart: always
