version: '3'
services:
  nginx:
    image: nginx
    ports:
      - 2333:2333
    links:
      - fpm
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/nginx.crt:/etc/nginx/nginx.crt:ro
      - ./nginx/nginx.key:/etc/nginx/nginx.key:ro
      - ./nextcloud:/var/www/html
    restart: always
    depends_on:
      - fpm

  fpm:
    image: nextcloud:fpm
    links:
      - mariadb
      - redis
    volumes:
      - ./nextcloud:/var/www/html
      - ./fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    environment:
      - MYSQL_PASSWORD=kuaizi
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=mariadb
      - REDIS_HOST=redis
    restart: always
    depends_on:
      - mariadb
      - redis

  mariadb:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./mariadb/data:/var/lib/mysql
      - ./mariadb/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
    environment:
      - MYSQL_ROOT_PASSWORD=kuaizi
      - MYSQL_PASSWORD=kuaizi
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    restart: always

  redis:
    image: redis
    restart: always

  cron:
    image: nextcloud:image-preview
    volumes:
      - ./nextcloud:/var/www/html
    entrypoint: /cron.sh
    restart: always
    depends_on:
      - mariadb
      - redis
